version: '3.8'

services:
  hlife-backend:
    build:
      context: .
      target: dev
    restart: unless-stopped
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
      - /app/node_modules
