version: '3.8'

services:
  hlife-backend:
    build:
      context: .
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - MONGO_URI=${MONGO_URI}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - OUTLOOK_USER=${OUTLOOK_USER}
      - OUTLOOK_PASSWORD=${OUTLOOK_PASSWORD}

    volumes:
      - './public/:/app/public'
